services:
  mysql:
    image: 'mysql:latest'
    container_name: 'thymeleaf_project'
    environment:
      - 'MYSQL_DATABASE=thymeleaf_project_mysql'
      - 'MYSQL_PASSWORD=dev@password'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=dev'
    ports:
      - '3306:3306'
