services:
  mysql:
    image: mysql:latest
    container_name: spring_thymeleaf_mysql
    environment:
      - MYSQL_DATABASE=thymeleaf_project_mysql
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev@password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: